/* ===== 問題データ（算数いがい） ===== */
/* choice形式: { q, answer, choices:[...] }  choicesの1つ目が正解でなくてもOK（app側でシャッフル） */

const DATA = {
  g1: {
    // こくご：ひらがな・かん字のよみ・ことば
    kokugo: [
      { q: "「山」の よみは？", answer: "やま", choices: ["やま","かわ","た","うみ"] },
      { q: "「川」の よみは？", answer: "かわ", choices: ["かわ","やま","いし","き"] },
      { q: "「日」の よみは？", answer: "ひ", choices: ["ひ","つき","ほし","そら"] },
      { q: "「月」の よみは？", answer: "つき", choices: ["つき","ひ","みず","き"] },
      { q: "「木」の よみは？", answer: "き", choices: ["き","はな","くさ","ゆき"] },
      { q: "「火」の よみは？", answer: "ひ", choices: ["ひ","みず","かぜ","つち"] },
      { q: "「水」の よみは？", answer: "みず", choices: ["みず","ひ","き","いし"] },
      { q: "「大」の よみは？", answer: "おお", choices: ["おお","ちい","なが","たか"] },
      { q: "「小」の よみは？", answer: "ちい", choices: ["ちい","おお","まる","しか"] },
      { q: "「上」の よみは？", answer: "うえ", choices: ["うえ","した","なか","そと"] },
      { q: "「下」の よみは？", answer: "した", choices: ["した","うえ","みぎ","ひだり"] },
      { q: "「right（みぎ）」を あらわす かん字は？", answer: "右", choices: ["右","左","中","手"] },
      { q: "「ねこ」を カタカナで かくと？", answer: "ネコ", choices: ["ネコ","ネユ","ヌコ","ネヨ"] },
      { q: "「いぬ」を カタカナで かくと？", answer: "イヌ", choices: ["イヌ","イマ","エヌ","イム"] },
      { q: "「あ」の つぎの ひらがなは？", answer: "い", choices: ["い","う","お","か"] },
      { q: "しりとり:「りんご」→ つぎは？", answer: "ごりら", choices: ["ごりら","りす","みかん","ばなな"] },
      { q: "「口」の よみは？", answer: "くち", choices: ["くち","め","みみ","て"] },
      { q: "「目」の よみは？", answer: "め", choices: ["め","くち","はな","あし"] },
      { q: "「手」の よみは？", answer: "て", choices: ["て","あし","かお","ゆび"] },
      { q: "「足」の よみは？", answer: "あし", choices: ["あし","て","くび","かた"] },
      { q: "「年」の よみは？", answer: "ねん", choices: ["ねん","つき","ひ","じ"] },
      { q: "「先生」の よみは？", answer: "せんせい", choices: ["せんせい","がくせい","ともだち","かぞく"] },
      { q: "「学校」の よみは？", answer: "がっこう", choices: ["がっこう","こうえん","びょういん","おてら"] },
      { q: "「花」の よみは？", answer: "はな", choices: ["はな","くさ","き","は"] },
      { q: "「石」の よみは？", answer: "いし", choices: ["いし","すな","つち","みず"] },
      { q: "「白」の よみは？", answer: "しろ", choices: ["しろ","くろ","あか","あお"] },
      { q: "「赤」の よみは？", answer: "あか", choices: ["あか","あお","きいろ","みどり"] },
      { q: "「せ」を カタカナで かくと？", answer: "セ", choices: ["セ","サ","ソ","シ"] },
      { q: "しりとり:「さかな」→ つぎは？", answer: "なす", choices: ["なす","さる","かに","くま"] },
      { q: "「くるま」を カタカナで かくと？", answer: "クルマ", choices: ["クルマ","クレマ","ワルマ","クルテ"] },
      { q: "「森」の よみは？", answer: "もり", choices: ["もり","はやし","やま","の"] },
      { q: "「雨」の よみは？", answer: "あめ", choices: ["あめ","ゆき","かぜ","くも"] },
      { q: "「空」の よみは？", answer: "そら", choices: ["そら","うみ","やま","つち"] },
      { q: "「金」の よみは？", answer: "かね", choices: ["かね","ぎん","てつ","どう"] },
      { q: "「男」の よみは？", answer: "おとこ", choices: ["おとこ","おんな","こども","おとな"] },
      { q: "「女」の よみは？", answer: "おんな", choices: ["おんな","おとこ","こ","はは"] },
      { q: "「大きい」の はんたいは？", answer: "小さい", choices: ["小さい","たかい","ながい","おもい"] },
      { q: "「おおい」の はんたいは？", answer: "すくない", choices: ["すくない","ちいさい","ひくい","おそい"] },
      { q: "「たかい」の はんたいは？", answer: "ひくい", choices: ["ひくい","みじかい","やすい","ふとい"] },
      { q: "「ながい」の はんたいは？", answer: "みじかい", choices: ["みじかい","おおきい","ひろい","たかい"] },
      { q: "「あつい」の はんたいは？", answer: "さむい", choices: ["さむい","つよい","くらい","おもい"] },
      { q: "ねこが 3□。□に 入る かぞえかたは？", answer: "びき", choices: ["びき","まい","こ","だい"] },
      { q: "えんぴつが 2□。□に 入る かぞえかたは？", answer: "ほん", choices: ["ほん","まい","ひき","さつ"] },
      { q: "本が 5□。□に 入る かぞえかたは？", answer: "さつ", choices: ["さつ","こ","だい","ひき"] },
      { q: "「五」の よみは？", answer: "ご", choices: ["ご","し","さん","ろく"] },
      { q: "「百」の よみは？", answer: "ひゃく", choices: ["ひゃく","せん","じゅう","まん"] },
      { q: "「町」の よみは？", answer: "まち", choices: ["まち","むら","もり","いえ"] },
      { q: "「文」の よみは？", answer: "ぶん", choices: ["ぶん","じ","ほん","え"] },
      { q: "「ライオン」を ひらがなに すると？", answer: "らいおん", choices: ["らいおん","らいのん","れいおん","らおいん"] },
      { q: "しりとり:「くま」→ つぎは？", answer: "まど", choices: ["まど","くも","さる","かに"] },
      { q: "「い」の まえの ひらがなは？", answer: "あ", choices: ["あ","う","え","か"] },
      { q: "「がっこう」を ただしく かくと？", answer: "がっこう", choices: ["がっこう","がつこう","かっこう","がっこお"] },
      { q: "「二」の よみは？", answer: "に", choices: ["に","いち","さん","し"] },
      { q: "「七」の よみは？", answer: "しち", choices: ["しち","はち","きゅう","ろく"] },
      { q: "「中」の よみは？", answer: "なか", choices: ["なか","うち","そと","まん"] },
      { q: "「王」の よみは？", answer: "おう", choices: ["おう","たま","こく","ど"] },
      { q: "「ちから」を あらわす かん字は？", answer: "力", choices: ["力","刀","九","方"] },
      { q: "「はやい」の はんたいは？", answer: "おそい", choices: ["おそい","ちいさい","よわい","ひくい"] },
      { q: "「あかるい」の はんたいは？", answer: "くらい", choices: ["くらい","おもい","つめたい","からい"] },
      { q: "「いれる」の はんたいは？", answer: "だす", choices: ["だす","とじる","おす","ひく"] },
      { q: "「うみ」を カタカナで かくと？", answer: "ウミ", choices: ["ウミ","ワミ","ウニ","ヴミ"] },
      { q: "「バス」を ひらがなに すると？", answer: "ばす", choices: ["ばす","はす","ぱす","ばず"] },
      { q: "花が 3□。□に 入る かぞえかたは？", answer: "りん", choices: ["りん","ひき","だい","こ"] },
      { q: "しりとり:「そら」→ つぎは？", answer: "らっぱ", choices: ["らっぱ","さかな","そり","くも"] },
      { q: "「right の はんたい（left）」は かん字で？", answer: "左", choices: ["左","右","中","下"] },
      { q: "「金」の よみは？", answer: "かね", choices: ["かね","つち","みず","いし"] },
      { q: "「休む」の よみは？", answer: "やすむ", choices: ["やすむ","すむ","のむ","よむ"] },
      { q: "「文字」の よみは？", answer: "もじ", choices: ["もじ","ぶんじ","もんじ","ことば"] },
    ],
    // えいご：あいさつ・数・いろ・どうぶつ
    english: [
      { q: "「おはよう」を えいごで？", answer: "Good morning", choices: ["Good morning","Good night","Thank you","Goodbye"] },
      { q: "「ありがとう」を えいごで？", answer: "Thank you", choices: ["Thank you","Hello","Sorry","Please"] },
      { q: "「あか」は えいごで？", answer: "red", choices: ["red","blue","green","yellow"] },
      { q: "「あお」は えいごで？", answer: "blue", choices: ["blue","red","black","white"] },
      { q: "「1」は えいごで？", answer: "one", choices: ["one","two","three","ten"] },
      { q: "「3」は えいごで？", answer: "three", choices: ["three","two","five","four"] },
      { q: "「ねこ」は えいごで？", answer: "cat", choices: ["cat","dog","fish","bird"] },
      { q: "「いぬ」は えいごで？", answer: "dog", choices: ["dog","cat","cow","pig"] },
      { q: "「りんご」は えいごで？", answer: "apple", choices: ["apple","banana","orange","grape"] },
      { q: "「Hello」の いみは？", answer: "こんにちは", choices: ["こんにちは","さようなら","ごめんね","おやすみ"] },
      { q: "「きいろ」は えいごで？", answer: "yellow", choices: ["yellow","green","pink","brown"] },
      { q: "「みどり」は えいごで？", answer: "green", choices: ["green","blue","red","black"] },
      { q: "「2」は えいごで？", answer: "two", choices: ["two","one","four","six"] },
      { q: "「5」は えいごで？", answer: "five", choices: ["five","four","nine","seven"] },
      { q: "「Goodbye」の いみは？", answer: "さようなら", choices: ["さようなら","こんにちは","おはよう","ありがとう"] },
      { q: "「とり」は えいごで？", answer: "bird", choices: ["bird","fish","cat","frog"] },
      { q: "「さかな」は えいごで？", answer: "fish", choices: ["fish","bird","dog","bear"] },
      { q: "「バナナ」は えいごで？", answer: "banana", choices: ["banana","apple","melon","lemon"] },
      { q: "「Cat」の いみは？", answer: "ねこ", choices: ["ねこ","いぬ","うさぎ","くま"] },
      { q: "「しろ」は えいごで？", answer: "white", choices: ["white","black","red","blue"] },
      { q: "「くろ」は えいごで？", answer: "black", choices: ["black","white","gray","green"] },
      { q: "「Dog」の いみは？", answer: "いぬ", choices: ["いぬ","ねこ","ぶた","うし"] },
      { q: "「4」は えいごで？", answer: "four", choices: ["four","five","three","eight"] },
      { q: "「10」は えいごで？", answer: "ten", choices: ["ten","two","twelve","nine"] },
      { q: "「6」は えいごで？", answer: "six", choices: ["six","seven","nine","four"] },
      { q: "「7」は えいごで？", answer: "seven", choices: ["seven","six","eight","ten"] },
      { q: "「8」は えいごで？", answer: "eight", choices: ["eight","nine","six","two"] },
      { q: "「みどり」は えいごで？", answer: "green", choices: ["green","blue","pink","brown"] },
      { q: "「ピンク」は えいごで？", answer: "pink", choices: ["pink","purple","red","gray"] },
      { q: "「くま」は えいごで？", answer: "bear", choices: ["bear","lion","dog","cat"] },
      { q: "「ぞう」は えいごで？", answer: "elephant", choices: ["elephant","horse","bear","mouse"] },
      { q: "「Rabbit」の いみは？", answer: "うさぎ", choices: ["うさぎ","かめ","きつね","ぶた"] },
      { q: "「Good night」の いみは？", answer: "おやすみ", choices: ["おやすみ","おはよう","こんにちは","ありがとう"] },
      { q: "「みかん」は えいごで？", answer: "orange", choices: ["orange","apple","lemon","peach"] },
      { q: "「たまご」は えいごで？", answer: "egg", choices: ["egg","milk","rice","bread"] },
      { q: "「Sorry」の いみは？", answer: "ごめんね", choices: ["ごめんね","ありがとう","またね","どうぞ"] },
      { q: "「9」は えいごで？", answer: "nine", choices: ["nine","five","ten","seven"] },
      { q: "「むらさき」は えいごで？", answer: "purple", choices: ["purple","pink","brown","gray"] },
      { q: "「ちゃいろ」は えいごで？", answer: "brown", choices: ["brown","black","blue","white"] },
      { q: "「うま」は えいごで？", answer: "horse", choices: ["horse","cow","pig","sheep"] },
      { q: "「とり」は えいごで？", answer: "bird", choices: ["bird","fish","frog","bee"] },
      { q: "「Fish」の いみは？", answer: "さかな", choices: ["さかな","とり","いぬ","ねこ"] },
      { q: "「Please」の いみは？", answer: "おねがい", choices: ["おねがい","ごめんね","ありがとう","またね"] },
      { q: "「あたま」は えいごで？", answer: "head", choices: ["head","hand","foot","eye"] },
      { q: "「て」は えいごで？", answer: "hand", choices: ["hand","head","leg","ear"] },
      { q: "「ぼうし」は えいごで？", answer: "hat", choices: ["hat","cap","bag","shoe"] },
      { q: "「Book」の いみは？", answer: "ほん", choices: ["ほん","つくえ","えんぴつ","かばん"] },
      { q: "「みず」は えいごで？", answer: "water", choices: ["water","milk","juice","tea"] },
    ],
    // せいかつ・クイズ
    other: [
      { q: "にじは いくつの いろ？", answer: "7つ", choices: ["7つ","3つ","5つ","10"] },
      { q: "ちょうちょは 何から うまれる？", answer: "たまご", choices: ["たまご","はっぱ","はな","つち"] },
      { q: "あさがおの たねを まく きせつは？", answer: "はる", choices: ["はる","なつ","あき","ふゆ"] },
      { q: "こおりが とけると 何になる？", answer: "みず", choices: ["みず","ゆき","くも","あめ"] },
      { q: "1しゅうかんは 何日？", answer: "7日", choices: ["7日","5日","10日","3日"] },
      { q: "みつばちが あつめるのは？", answer: "みつ", choices: ["みつ","みず","すな","くさ"] },
      { q: "なつに たくさん なく むしは？", answer: "せみ", choices: ["せみ","こおろぎ","すずむし","とんぼ"] },
      { q: "しんごうの「すすめ」の いろは？", answer: "みどり(あお)", choices: ["みどり(あお)","あか","きいろ","しろ"] },
      { q: "たまごを うむ どうぶつは？", answer: "にわとり", choices: ["にわとり","いぬ","ねこ","うし"] },
      { q: "1年は 何かげつ？", answer: "12かげつ", choices: ["12かげつ","10かげつ","7かげつ","24かげつ"] },
      { q: "おたまじゃくしは 大きくなると？", answer: "かえる", choices: ["かえる","さかな","へび","とり"] },
      { q: "よるに 空で ひかるのは？", answer: "つき・ほし", choices: ["つき・ほし","たいよう","にじ","くも"] },
      { q: "はをみがくのは いつ？", answer: "あさとよる", choices: ["あさとよる","ひるだけ","よるだけ","いつでもよい"] },
      { q: "あさがおの 花は 何いろが おおい？", answer: "むらさき・あお", choices: ["むらさき・あお","くろ","ちゃいろ","はいいろ"] },
      { q: "ひまわりは どっちを むく？", answer: "たいようのほう", choices: ["たいようのほう","つちのなか","きたのほう","みずのほう"] },
      { q: "かたつむりが せなかに もつのは？", answer: "から(いえ)", choices: ["から(いえ)","はね","つの2ほんだけ","しっぽ"] },
      { q: "たんぽぽの わたげは 何で とぶ？", answer: "かぜ", choices: ["かぜ","みず","ひかり","おと"] },
      { q: "こおりを つくるには？", answer: "ひやす", choices: ["ひやす","あたためる","ひにあてる","ふる"] },
      { q: "はるに さく 花は？", answer: "さくら", choices: ["さくら","ひまわり","コスモス","すいせん"] },
      { q: "牛から とれる のみものは？", answer: "ぎゅうにゅう", choices: ["ぎゅうにゅう","ジュース","おちゃ","みず"] },
      { q: "1日は なんじかん？", answer: "24じかん", choices: ["24じかん","12じかん","10じかん","60じかん"] },
      { q: "かみなりの あとに 聞こえるのは？", answer: "ゴロゴロという音", choices: ["ゴロゴロという音","うたごえ","かねの音","なにもない"] },
      { q: "やさいは どこで そだつ？", answer: "はたけ・畑", choices: ["はたけ・畑","うみ","そら","いえの中だけ"] },
      { q: "でんきを つけるものは？", answer: "スイッチ", choices: ["スイッチ","ドア","まど","とけい"] },
      { q: "あめの日に そらに かかることがあるのは？", answer: "にじ", choices: ["にじ","ゆき","つき","ほし"] },
      { q: "カブトムシが すきな 木の しるは？", answer: "じゅえき（木のしる）", choices: ["じゅえき（木のしる）","ミルク","ジュース","みつ豆"] },
      { q: "1年で いちばん さむい きせつは？", answer: "ふゆ", choices: ["ふゆ","なつ","はる","あき"] },
      { q: "たねから さいしょに 出てくるのは？", answer: "め（芽）", choices: ["め（芽）","はな","み","えだ"] },
      { q: "でんきを 使う どうぐは？", answer: "テレビ", choices: ["テレビ","えんぴつ","ボール","コップ"] },
      { q: "あさに 東から のぼるのは？", answer: "たいよう", choices: ["たいよう","つき","ほし","くも"] },
      { q: "みずに うかぶのは どっち？", answer: "木のは", choices: ["木のは","いし","くぎ","じしゃく"] },
      { q: "ありは どこに すんでいる？", answer: "つちの中", choices: ["つちの中","うみの中","そらの上","木のてっぺんだけ"] },
      { q: "かえるは 大きくなる まえは？", answer: "おたまじゃくし", choices: ["おたまじゃくし","たまごのまま","さかな","へび"] },
      { q: "しゃぼんだまは 何で できる？", answer: "せっけんと 水", choices: ["せっけんと 水","すなと 水","こおり","つち"] },
      { q: "きせつの じゅんばん。はる→なつ→□→ふゆ", answer: "あき", choices: ["あき","はる","なつ","つゆ"] },
      { q: "よるに 光って とぶ むしは？", answer: "ほたる", choices: ["ほたる","せみ","ちょうちょ","あり"] },
      { q: "はっぱの 色は なつは？", answer: "みどり", choices: ["みどり","あか","きいろ","ちゃいろ"] },
      { q: "かさを つかうのは どんな 日？", answer: "あめの日", choices: ["あめの日","はれの日","かぜの日だけ","ゆきは いらない"] },
    ],
  },

  g5: {
    // 国語：漢字の読み・四字熟語・慣用句・対義語
    kokugo: [
      { q: "「快晴」の読みは？", answer: "かいせい", choices: ["かいせい","かいばれ","こころよい","はれま"] },
      { q: "「往復」の読みは？", answer: "おうふく", choices: ["おうふく","おうもど","ゆきかえり","おうへん"] },
      { q: "「効果」の「効」を使う正しい熟語は？", answer: "効果", choices: ["効果","功績","校庭","交代"] },
      { q: "「暴風」の読みは？", answer: "ぼうふう", choices: ["ぼうふう","あばれかぜ","ばくふう","ぼうかぜ"] },
      { q: "四字熟語「一石二□」の□は？", answer: "鳥", choices: ["鳥","羽","石","矢"] },
      { q: "四字熟語「十人十□」の□は？", answer: "色", choices: ["色","人","様","面"] },
      { q: "四字熟語「絶体絶□」の□は？", answer: "命", choices: ["命","体","対","望"] },
      { q: "「花を持たせる」の意味は？", answer: "手がらをゆずる", choices: ["手がらをゆずる","じゃまをする","急いで帰る","花をかざる"] },
      { q: "「油を売る」の意味は？", answer: "むだ話をしてなまける", choices: ["むだ話をしてなまける","一生けん命はたらく","油をこぼす","料理をする"] },
      { q: "「河口」の読みは？", answer: "かこう", choices: ["かこう","かわぐち","がこう","かくち"] },
      { q: "「規則」の読みは？", answer: "きそく", choices: ["きそく","きぞく","のりのり","ていそく"] },
      { q: "「複数」の対義語は？", answer: "単数", choices: ["単数","少数","多数","分数"] },
      { q: "「増加」の対義語は？", answer: "減少", choices: ["減少","増大","加速","低下"] },
      { q: "「開始」の対義語は？", answer: "終了", choices: ["終了","中止","開放","始発"] },
      { q: "「賛成」の対義語は？", answer: "反対", choices: ["反対","同意","賛同","可決"] },
      { q: "四字熟語「一日千□」の□は？", answer: "秋", choices: ["秋","里","円","金"] },
      { q: "四字熟語「自□自賛」の□は？", answer: "画", choices: ["画","分","作","満"] },
      { q: "「耳を貸す」の意味は？", answer: "話を聞いてあげる", choices: ["話を聞いてあげる","わざと無視する","耳をふさぐ","大声を出す"] },
      { q: "「馬が合う」の意味は？", answer: "気が合う", choices: ["気が合う","けんかする","足がはやい","馬にのる"] },
      { q: "「快い」の読みは？", answer: "こころよい", choices: ["こころよい","かるい","はやい","つよい"] },
      { q: "「険しい」の読みは？", answer: "けわしい", choices: ["けわしい","あやしい","きびしい","くるしい"] },
      { q: "「境界」の読みは？", answer: "きょうかい", choices: ["きょうかい","さかいめ","きょうがい","けいかい"] },
      { q: "「往路」の対義語は？", answer: "復路", choices: ["復路","帰路","進路","通路"] },
      { q: "「原因」の対義語は？", answer: "結果", choices: ["結果","理由","原点","要因"] },
      { q: "「団結」の「団」と同じ読みの漢字は？", answer: "集団の団", choices: ["集団の団","段だんの段","男の男","談話の談"] },
      { q: "四字熟語「以心□心」の□は？", answer: "伝", choices: ["伝","電","点","天"] },
      { q: "「みなもと」を表す漢字は？", answer: "源", choices: ["源","泉","液","流"] },
      { q: "「講堂」の読みは？", answer: "こうどう", choices: ["こうどう","こうとう","きょうどう","こうじょう"] },
      { q: "「幹」の読みは？", answer: "みき", choices: ["みき","えだ","ね","は"] },
      { q: "「耕す」の読みは？", answer: "たがやす", choices: ["たがやす","おかす","ほどこす","たがえす"] },
      { q: "「営む」の読みは？", answer: "いとなむ", choices: ["いとなむ","いどむ","いとしむ","おがむ"] },
      { q: "「群れ」の読みは？", answer: "むれ", choices: ["むれ","ぐん","かたまり","たば"] },
      { q: "四字熟語「臨機応□」の□は？", answer: "変", choices: ["変","対","転","化"] },
      { q: "四字熟語「品行方□」の□は？", answer: "正", choices: ["正","直","確","当"] },
      { q: "四字熟語「因果応□」の□は？", answer: "報", choices: ["報","答","返","対"] },
      { q: "「猫の手も借りたい」の意味は？", answer: "とても いそがしい", choices: ["とても いそがしい","ねこが すき","とても ひま","手つだいが 多い"] },
      { q: "「手を焼く」の意味は？", answer: "あつかいに こまる", choices: ["あつかいに こまる","料理を する","やけどを する","一生けん命 やる"] },
      { q: "「理想」の対義語は？", answer: "現実", choices: ["現実","空想","理論","実行"] },
      { q: "「積極的」の対義語は？", answer: "消極的", choices: ["消極的","意欲的","積極性","感動的"] },
      { q: "「有名」の類義語は？", answer: "著名", choices: ["著名","無名","評価","名前"] },
      { q: "「池」の部首は？", answer: "さんずい", choices: ["さんずい","つちへん","にすい","き"] },
      { q: "「花」の部首は？", answer: "くさかんむり", choices: ["くさかんむり","はなへん","うかんむり","き"] },
      { q: "「保健」の「保」と 同じ部首の 漢字は？", answer: "係", choices: ["係","線","持","板"] },
      { q: "「確率」の読みは？", answer: "かくりつ", choices: ["かくりつ","かくそつ","たしりつ","かくりゅう"] },
      { q: "「快適」の読みは？", answer: "かいてき", choices: ["かいてき","けってき","かいきん","こころよい"] },
      { q: "「災害」の読みは？", answer: "さいがい", choices: ["さいがい","さいばい","さんがい","せいがい"] },
      { q: "「肥料」の読みは？", answer: "ひりょう", choices: ["ひりょう","ひりょ","こえりょう","ひろう"] },
      { q: "「独立」の読みは？", answer: "どくりつ", choices: ["どくりつ","どくたつ","とくりつ","ひとりだち"] },
      { q: "「精」の読みで 正しいのは（精神）？", answer: "せい", choices: ["せい","しょう","あお","きよ"] },
      { q: "四字熟語「半信半□」の□は？", answer: "疑", choices: ["疑","偽","義","議"] },
      { q: "四字熟語「油断大□」の□は？", answer: "敵", choices: ["敵","的","適","滴"] },
      { q: "四字熟語「一長一□」の□は？", answer: "短", choices: ["短","長","方","面"] },
      { q: "「口が かたい」の意味は？", answer: "ひみつを守る", choices: ["ひみつを守る","よく食べる","よくしゃべる","歯が丈夫"] },
      { q: "「気が置けない」の意味は？", answer: "えんりょが いらない", choices: ["えんりょが いらない","ゆだんできない","きけんだ","気にくわない"] },
      { q: "「暑い」の対義語は？", answer: "寒い", choices: ["寒い","冷たい","暖かい","涼しい"] },
      { q: "「往来」の類義語は？", answer: "行き来", choices: ["行き来","道路","おうふく","通行止め"] },
      { q: "「消しゴム」の「消」の部首は？", answer: "さんずい", choices: ["さんずい","ひへん","つきへん","くさかんむり"] },
      { q: "「賞」の 総画数は？", answer: "15画", choices: ["15画","13画","12画","16画"] },
    ],
    // 英語：単語・意味・曜日・文
    english: [
      { q: "「social studies」の意味は？", answer: "社会", choices: ["社会","算数","音楽","体育"] },
      { q: "「うれしい」は英語で？", answer: "happy", choices: ["happy","sad","angry","sleepy"] },
      { q: "「月曜日」は英語で？", answer: "Monday", choices: ["Monday","Sunday","Friday","Tuesday"] },
      { q: "「Wednesday」は何曜日？", answer: "水曜日", choices: ["水曜日","木曜日","火曜日","土曜日"] },
      { q: "「学校」は英語で？", answer: "school", choices: ["school","house","park","shop"] },
      { q: "「先生」は英語で？", answer: "teacher", choices: ["teacher","student","doctor","driver"] },
      { q: "「大きい」は英語で？", answer: "big", choices: ["big","small","long","short"] },
      { q: "「What time is it?」の意味は？", answer: "何時ですか？", choices: ["何時ですか？","元気ですか？","名前は？","どこ？"] },
      { q: "「12」は英語で？", answer: "twelve", choices: ["twelve","twenty","eleven","two"] },
      { q: "「triangle」の意味は？", answer: "三角形", choices: ["三角形","円","四角形","直線"] },
      { q: "「science」の意味は？", answer: "理科", choices: ["理科","社会","国語","家庭科"] },
      { q: "「かなしい」は英語で？", answer: "sad", choices: ["sad","happy","fun","kind"] },
      { q: "「金曜日」は英語で？", answer: "Friday", choices: ["Friday","Thursday","Saturday","Monday"] },
      { q: "「Sunday」は何曜日？", answer: "日曜日", choices: ["日曜日","土曜日","月曜日","水曜日"] },
      { q: "「小さい」は英語で？", answer: "small", choices: ["small","big","tall","wide"] },
      { q: "「How are you?」の意味は？", answer: "元気ですか？", choices: ["元気ですか？","何歳ですか？","どこ？","何時？"] },
      { q: "「20」は英語で？", answer: "twenty", choices: ["twenty","twelve","thirty","two"] },
      { q: "「circle」の意味は？", answer: "円", choices: ["円","三角形","四角形","星"] },
      { q: "「library」の意味は？", answer: "図書館", choices: ["図書館","病院","学校","公園"] },
      { q: "「friend」の意味は？", answer: "友だち", choices: ["友だち","家族","先生","医者"] },
      { q: "「water」の意味は？", answer: "水", choices: ["水","火","風","土"] },
      { q: "「My name is Ken.」の意味は？", answer: "私の名前はケンです", choices: ["私の名前はケンです","ケンが好きです","ケンはどこ？","ケンは元気です"] },
      { q: "「うつくしい」は英語で？", answer: "beautiful", choices: ["beautiful","dirty","fast","strong"] },
      { q: "「breakfast」の意味は？", answer: "朝ごはん", choices: ["朝ごはん","昼ごはん","夜ごはん","おやつ"] },
      { q: "「Thursday」は何曜日？", answer: "木曜日", choices: ["木曜日","水曜日","金曜日","火曜日"] },
      { q: "「long」の意味は？", answer: "長い", choices: ["長い","短い","高い","低い"] },
      { q: "「春」は英語で？", answer: "spring", choices: ["spring","summer","autumn","winter"] },
      { q: "「冬」は英語で？", answer: "winter", choices: ["winter","summer","spring","fall"] },
      { q: "「Tuesday」は何曜日？", answer: "火曜日", choices: ["火曜日","木曜日","土曜日","月曜日"] },
      { q: "「Saturday」は何曜日？", answer: "土曜日", choices: ["土曜日","日曜日","金曜日","水曜日"] },
      { q: "「昼食」は英語で？", answer: "lunch", choices: ["lunch","dinner","breakfast","snack"] },
      { q: "「夕食」は英語で？", answer: "dinner", choices: ["dinner","lunch","breakfast","meal"] },
      { q: "「正方形」は英語で？", answer: "square", choices: ["square","circle","triangle","rectangle"] },
      { q: "「30」は英語で？", answer: "thirty", choices: ["thirty","thirteen","forty","twenty"] },
      { q: "「100」は英語で？", answer: "hundred", choices: ["hundred","thousand","hundreds","ten"] },
      { q: "「I like soccer.」の意味は？", answer: "サッカーが 好きです", choices: ["サッカーが 好きです","サッカーを します","サッカーは きらい","サッカーが 上手"] },
      { q: "「vegetable」の意味は？", answer: "やさい", choices: ["やさい","くだもの","にく","さかな"] },
      { q: "「station」の意味は？", answer: "えき", choices: ["えき","空港","びょういん","こうえん"] },
      { q: "「October」は何月？", answer: "10月", choices: ["10月","8月","12月","9月"] },
      { q: "「7月」は英語で？", answer: "July", choices: ["July","June","January","March"] },
      { q: "「rainy」の意味は？", answer: "雨の", choices: ["雨の","晴れの","くもりの","雪の"] },
      { q: "「morning」の意味は？", answer: "朝", choices: ["朝","昼","夜","夕方"] },
      { q: "「hospital」の意味は？", answer: "病院", choices: ["病院","学校","図書館","公園"] },
      { q: "「animal」の意味は？", answer: "動物", choices: ["動物","植物","食べ物","乗り物"] },
      { q: "「Let's play.」の意味は？", answer: "あそぼう", choices: ["あそぼう","食べよう","行こう","見よう"] },
      { q: "「fast」の意味は？", answer: "速い", choices: ["速い","おそい","強い","高い"] },
      { q: "「right（方向）」の意味は？", answer: "右", choices: ["右","左","前","後ろ"] },
      { q: "「300」は英語で？", answer: "three hundred", choices: ["three hundred","thirty","three thousand","thirteen"] },
      { q: "「family」の意味は？", answer: "家族", choices: ["家族","友だち","先生","近所"] },
      { q: "「eleven」は いくつ？", answer: "11", choices: ["11","12","7","9"] },
    ],
    // 理科・社会・都道府県
    other: [
      { q: "日本で いちばん高い山は？", answer: "富士山", choices: ["富士山","立山","白山","阿蘇山"] },
      { q: "北海道の県庁所在地は？", answer: "札幌市", choices: ["札幌市","函館市","旭川市","釧路市"] },
      { q: "「金閣寺」がある都道府県は？", answer: "京都府", choices: ["京都府","奈良県","大阪府","滋賀県"] },
      { q: "植物が 光を使って養分をつくることを何という？", answer: "光合成", choices: ["光合成","呼吸","蒸散","発芽"] },
      { q: "水が水じょう気になることを？", answer: "じょう発", choices: ["じょう発","ぎょうこ","ゆうかい","ぎょうけつ"] },
      { q: "太陽・地球・月。月が回っているのは？", answer: "地球", choices: ["地球","太陽","星","雲"] },
      { q: "米づくりが さかんな地方といえば？", answer: "東北地方", choices: ["東北地方","九州地方","四国地方","中国地方"] },
      { q: "方位じしんの N が さすのは？", answer: "北", choices: ["北","南","東","西"] },
      { q: "食べ物を消化する えきを出す いちばん大きい臓器は？", answer: "かん臓", choices: ["かん臓","心臓","はい","じん臓"] },
      { q: "日本一 大きい湖は？", answer: "びわ湖", choices: ["びわ湖","かすみがうら","さろま湖","はまな湖"] },
      { q: "水が こおることを 何という？", answer: "ぎょうこ", choices: ["ぎょうこ","じょう発","ゆうかい","ふっとう"] },
      { q: "けん玉ではなく、日本一 人口が多い都道府県は？", answer: "東京都", choices: ["東京都","大阪府","神奈川県","愛知県"] },
      { q: "みかんの さいばいで 有名な県は？", answer: "和歌山県", choices: ["和歌山県","青森県","山形県","長野県"] },
      { q: "りんごの さいばいで 日本一の県は？", answer: "青森県", choices: ["青森県","和歌山県","静岡県","宮崎県"] },
      { q: "心ぞうの はたらきは？", answer: "血液を送り出す", choices: ["血液を送り出す","食べ物を消化する","空気を すう","にょうを作る"] },
      { q: "台風は どの きせつに 多い？", answer: "夏〜秋", choices: ["夏〜秋","冬","春さきだけ","一年中同じ"] },
      { q: "沖縄県の 県庁所在地は？", answer: "那覇市", choices: ["那覇市","名護市","石垣市","浦添市"] },
      { q: "日本を ながれる いちばん長い川は？", answer: "信濃川", choices: ["信濃川","利根川","石狩川","北上川"] },
      { q: "月の 形が 毎日 少しずつ かわるのを 何という？", answer: "月の満ち欠け", choices: ["月の満ち欠け","日食","月食","流星"] },
      { q: "植物の 葉から 水が出ていくことを？", answer: "蒸散", choices: ["蒸散","光合成","呼吸","発芽"] },
      { q: "自動車の せいさんが さかんな県は？", answer: "愛知県", choices: ["愛知県","北海道","沖縄県","高知県"] },
      { q: "電気を 通すものは どれ？", answer: "鉄のクギ", choices: ["鉄のクギ","木のわりばし","ガラスのコップ","プラスチックのじょうぎ"] },
      { q: "日本で いちばん 面積が 大きい都道府県は？", answer: "北海道", choices: ["北海道","岩手県","福島県","長野県"] },
      { q: "太陽が のぼる方角は？", answer: "東", choices: ["東","西","南","北"] },
      { q: "宮城県の 県庁所在地は？", answer: "仙台市", choices: ["仙台市","盛岡市","福島市","山形市"] },
      { q: "愛知県の 県庁所在地は？", answer: "名古屋市", choices: ["名古屋市","豊田市","岐阜市","静岡市"] },
      { q: "兵庫県の 県庁所在地は？", answer: "神戸市", choices: ["神戸市","大阪市","姫路市","京都市"] },
      { q: "「うどん」で 有名な県は？", answer: "香川県", choices: ["香川県","愛媛県","徳島県","高知県"] },
      { q: "「さくらんぼ」の 生産で 有名な県は？", answer: "山形県", choices: ["山形県","青森県","長野県","福島県"] },
      { q: "世界遺産「厳島神社」が ある県は？", answer: "広島県", choices: ["広島県","山口県","岡山県","島根県"] },
      { q: "ふりこが 1往復する 時間は 何で 決まる？", answer: "ひもの 長さ", choices: ["ひもの 長さ","おもりの 重さ","ふれはば","ひもの 色"] },
      { q: "金属の 熱の つたわり方を 何という？", answer: "伝導", choices: ["伝導","対流","放射","蒸発"] },
      { q: "電磁石の 力を 強くするには？", answer: "電流を 大きくする", choices: ["電流を 大きくする","みじかくする","じしゃくを へらす","銅線を 細くする"] },
      { q: "種子の 発芽に 必要ないものは？", answer: "日光", choices: ["日光","水","空気","てきとうな 温度"] },
      { q: "川の 上流の 石の とくちょうは？", answer: "大きくて 角ばっている", choices: ["大きくて 角ばっている","小さくて 丸い","すなばかり","石がない"] },
      { q: "日本の 首都は？", answer: "東京", choices: ["東京","大阪","京都","横浜"] },
      { q: "法律を つくる 国の きかんは？", answer: "国会", choices: ["国会","内閣","裁判所","市役所"] },
      { q: "日本国憲法の 3つの原則の 1つは？", answer: "国民主権", choices: ["国民主権","王様主権","軍隊主権","会社主権"] },
      { q: "台風の 目の 中の 天気は？", answer: "風が 弱く 晴れることが 多い", choices: ["風が 弱く 晴れることが 多い","いちばん 雨が 強い","かならず 雪","かわらない"] },
      { q: "静岡県の 名産で 有名なのは？", answer: "お茶", choices: ["お茶","りんご","みかん","ぶどう"] },
      { q: "「阿波おどり」で 有名な県は？", answer: "徳島県", choices: ["徳島県","高知県","愛媛県","香川県"] },
      { q: "福岡県の 県庁所在地は？", answer: "福岡市", choices: ["福岡市","北九州市","久留米市","博多市"] },
      { q: "本州・北海道・九州と あと1つの 大きな島は？", answer: "四国", choices: ["四国","沖縄","佐渡","淡路島"] },
      { q: "食塩水から 水を じょう発させると 残るのは？", answer: "食塩", choices: ["食塩","さとう","なにも残らない","こおり"] },
      { q: "けんび鏡で 見るときの 順番。まず 何を 調節？", answer: "明るさ（反しゃ鏡）", choices: ["明るさ（反しゃ鏡）","ピント","ばいりつ","プレパラート"] },
      { q: "植物の 水や 養分の 通り道を 何という？", answer: "くだ（維管束）", choices: ["くだ（維管束）","根毛","気こう","葉緑体"] },
      { q: "空気中に いちばん 多い 気体は？", answer: "ちっ素", choices: ["ちっ素","酸素","二酸化炭素","水素"] },
      { q: "ものが 燃えるのに 必要な 気体は？", answer: "酸素", choices: ["酸素","ちっ素","二酸化炭素","水素"] },
      { q: "日本の お金を 発行しているのは？", answer: "日本銀行", choices: ["日本銀行","国会","ゆうびん局","市役所"] },
      { q: "選挙で 投票できるのは 何才から？（今）", answer: "18才", choices: ["18才","20才","16才","15才"] },
      { q: "地図で 山の 高さが 同じ ところを つないだ線は？", answer: "等高線", choices: ["等高線","経線","緯線","県境"] },
      { q: "冬に 雪が 多い 地方は？", answer: "日本海側", choices: ["日本海側","太平洋側","南の島","内陸だけ"] },
      { q: "川が はこんだ 土や すなが つもって できる 平地は？", answer: "へいや（平野）", choices: ["へいや（平野）","山地","高原","盆地"] },
    ],
  },
};

/* バッジ定義 */
const BADGES = [
  { id: "first",     emoji: "🌱", name: "はじめの一歩", desc: "はじめて クリア" },
  { id: "streak3",   emoji: "🔥", name: "3日れんぞく",  desc: "3日つづけた" },
  { id: "streak7",   emoji: "⭐", name: "7日れんぞく",  desc: "7日つづけた" },
  { id: "perfect",   emoji: "💯", name: "ぜんもん正かい", desc: "10問ぜんぶ正かい" },
  { id: "coins100",  emoji: "🪙", name: "コイン100",   desc: "コイン100まい" },
  { id: "coins500",  emoji: "👑", name: "コイン500",   desc: "コイン500まい" },
  { id: "math50",    emoji: "🧮", name: "さんすう名人", desc: "算数を50問" },
  { id: "allsubj",   emoji: "🌈", name: "ぜん教科",     desc: "4教科ぜんぶ体けん" },
  { id: "review10",  emoji: "🩹", name: "ふくしゅう王", desc: "にがてを10問こくふく" },
  { id: "shopper",   emoji: "🛍️", name: "はじめてのお買いもの", desc: "ショップで こうかん" },
  { id: "writer",    emoji: "✍️", name: "かきとり名人", desc: "20文字れんしゅう" },
  { id: "speed",     emoji: "⚡", name: "スピードスター", desc: "タイムアタックで15問正かい" },
];

/* 教科メニュー */
const SUBJECTS = {
  g1: [
    { id: "math",    emoji: "🧮", name: "さんすう", desc: "たしざん・ひきざん・とけい" },
    { id: "kokugo",  emoji: "🈵", name: "こくご",   desc: "ひらがな・かん字" },
    { id: "english", emoji: "🔤", name: "えいご",   desc: "あいさつ・かず・いろ" },
    { id: "other",   emoji: "🔬", name: "クイズ",   desc: "せいかつ・しぜん" },
  ],
  g5: [
    { id: "math",    emoji: "🧮", name: "算数",     desc: "分数・小数・割合・面積" },
    { id: "kokugo",  emoji: "📖", name: "国語",     desc: "漢字・四字熟語・慣用句" },
    { id: "english", emoji: "🔤", name: "英語",     desc: "単語・曜日・意味" },
    { id: "other",   emoji: "🌏", name: "理科・社会", desc: "都道府県・しくみ" },
  ],
};

/* ===== ショップ：アバター＆テーマ（コインでこうかん） ===== */
const SHOP = {
  avatars: [
    { id: "kid",     emoji: "🧒", name: "こども",     price: 0 },
    { id: "cat",     emoji: "🐱", name: "ねこ",       price: 50 },
    { id: "dog",     emoji: "🐶", name: "いぬ",       price: 50 },
    { id: "rabbit",  emoji: "🐰", name: "うさぎ",     price: 80 },
    { id: "bear",    emoji: "🐻", name: "くま",       price: 80 },
    { id: "fox",     emoji: "🦊", name: "きつね",     price: 120 },
    { id: "panda",   emoji: "🐼", name: "パンダ",     price: 120 },
    { id: "penguin", emoji: "🐧", name: "ペンギン",   price: 150 },
    { id: "lion",    emoji: "🦁", name: "ライオン",   price: 200 },
    { id: "unicorn", emoji: "🦄", name: "ユニコーン", price: 300 },
    { id: "dragon",  emoji: "🐉", name: "ドラゴン",   price: 400 },
    { id: "robot",   emoji: "🤖", name: "ロボット",   price: 400 },
    { id: "frog",    emoji: "🐸", name: "かえる",     price: 80 },
    { id: "cow",     emoji: "🐮", name: "うし",       price: 80 },
    { id: "pig",     emoji: "🐷", name: "ぶた",       price: 80 },
    { id: "chick",   emoji: "🐣", name: "ひよこ",     price: 100 },
    { id: "monkey",  emoji: "🐵", name: "さる",       price: 100 },
    { id: "bee",     emoji: "🐝", name: "はち",       price: 100 },
    { id: "hamster", emoji: "🐹", name: "ハムスター", price: 120 },
    { id: "horse",   emoji: "🐴", name: "うま",       price: 120 },
    { id: "koala",   emoji: "🐨", name: "コアラ",     price: 120 },
    { id: "turtle",  emoji: "🐢", name: "かめ",       price: 120 },
    { id: "tiger",   emoji: "🐯", name: "とら",       price: 150 },
    { id: "owl",     emoji: "🦉", name: "ふくろう",   price: 150 },
    { id: "octopus", emoji: "🐙", name: "たこ",       price: 150 },
    { id: "ghost",   emoji: "👻", name: "おばけ",     price: 150 },
    { id: "dolphin", emoji: "🐬", name: "いるか",     price: 200 },
    { id: "butterfly", emoji: "🦋", name: "ちょうちょ", price: 200 },
    { id: "shark",   emoji: "🦈", name: "さめ",       price: 250 },
    { id: "whale",   emoji: "🐳", name: "くじら",     price: 250 },
    { id: "fairy",   emoji: "🧚", name: "ようせい",   price: 300 },
    { id: "alien",   emoji: "👽", name: "うちゅうじん", price: 300 },
    { id: "hero",    emoji: "🦸", name: "ヒーロー",   price: 350 },
    { id: "ninja",   emoji: "🥷", name: "にんじゃ",   price: 350 },
    { id: "wizard",  emoji: "🧙", name: "まほうつかい", price: 500 },
  ],
  themes: [
    { id: "orange", name: "サンオレンジ", price: 0,
      vars: { "--bg":"#fff7ec","--bg2":"#ffe9cf","--ink":"#3a2b1a","--ink-soft":"#7a6a55","--orange":"#ff8a3d","--orange-d":"#ef6c1a","--card":"#ffffff" } },
    { id: "ocean", name: "うみブルー", price: 100,
      vars: { "--bg":"#eaf6ff","--bg2":"#cfe9ff","--ink":"#173049","--ink-soft":"#5b7186","--orange":"#3aa0ff","--orange-d":"#1f7fd8","--card":"#ffffff" } },
    { id: "forest", name: "もりグリーン", price: 100,
      vars: { "--bg":"#eefaef","--bg2":"#d3f0d6","--ink":"#1e3a24","--ink-soft":"#5e7a63","--orange":"#34c759","--orange-d":"#24a047","--card":"#ffffff" } },
    { id: "sakura", name: "さくらピンク", price: 150,
      vars: { "--bg":"#fff0f5","--bg2":"#ffd9e6","--ink":"#4a2333","--ink-soft":"#8a6572","--orange":"#ff6fa5","--orange-d":"#e84f89","--card":"#ffffff" } },
    { id: "grape", name: "ぶどうパープル", price: 150,
      vars: { "--bg":"#f4efff","--bg2":"#e2d5ff","--ink":"#2e2246","--ink-soft":"#6d6386","--orange":"#a06bff","--orange-d":"#7f45e0","--card":"#ffffff" } },
    { id: "night", name: "よぞらダーク", price: 250,
      vars: { "--bg":"#1e2233","--bg2":"#141826","--ink":"#f2f4fb","--ink-soft":"#a6adc4","--orange":"#ffb03d","--orange-d":"#e88a12","--card":"#2a2f45" } },
    { id: "lemon", name: "レモンイエロー", price: 100,
      vars: { "--bg":"#fffdf0","--bg2":"#fff2bf","--ink":"#4a4520","--ink-soft":"#8a835a","--orange":"#e6a400","--orange-d":"#c98600","--card":"#ffffff" } },
    { id: "sky", name: "そらシアン", price: 100,
      vars: { "--bg":"#eef9ff","--bg2":"#cdeeff","--ink":"#153244","--ink-soft":"#5a7a8a","--orange":"#1fb0d6","--orange-d":"#128aad","--card":"#ffffff" } },
    { id: "strawberry", name: "いちごレッド", price: 150,
      vars: { "--bg":"#fff2f3","--bg2":"#ffd4d8","--ink":"#4a1f24","--ink-soft":"#8a5c60","--orange":"#ff4d5e","--orange-d":"#e02f43","--card":"#ffffff" } },
    { id: "mint", name: "ミントグリーン", price: 150,
      vars: { "--bg":"#eefcf7","--bg2":"#cbf2e5","--ink":"#123a30","--ink-soft":"#5a8074","--orange":"#12b28a","--orange-d":"#0d9070","--card":"#ffffff" } },
    { id: "mono", name: "モノクロ", price: 200,
      vars: { "--bg":"#f4f4f5","--bg2":"#e0e0e4","--ink":"#212126","--ink-soft":"#6b6b73","--orange":"#48484f","--orange-d":"#2c2c31","--card":"#ffffff" } },
    { id: "space", name: "うちゅうパープル", price: 300,
      vars: { "--bg":"#1b1930","--bg2":"#12101f","--ink":"#f1effb","--ink-soft":"#a8a3c8","--orange":"#b96bff","--orange-d":"#9a45e8","--card":"#272242" } },
  ],
};

/* ===== かきとり（手書きなぞり練習）用の文字セット ===== */
const _chars = (s) => s.split("").map((c) => ({ c, yomi: c }));
// 「漢字(よみ)」形式の文字列 → [{c,yomi}]
const _kanji = (s) => s.trim().split(/\s+/).map((t) => {
  const m = t.match(/^(.)[（(](.+)[）)]$/);
  return m ? { c: m[1], yomi: m[2] } : { c: t[0], yomi: t[0] };
});

const WRITING_SETS = {
  g1: [
    { id: "hira", emoji: "あ", name: "ひらがな",
      chars: _chars("あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん") },
    { id: "kata", emoji: "ア", name: "カタカナ",
      chars: _chars("アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン") },
    { id: "kanji", emoji: "一", name: "かん字（1年）",
      chars: _kanji(`一(いち) 右(みぎ) 雨(あめ) 円(えん) 王(おう) 音(おと) 下(した) 火(ひ) 花(はな) 貝(かい)
        学(がく) 気(き) 九(きゅう) 休(やすむ) 玉(たま) 金(かね) 空(そら) 月(つき) 犬(いぬ) 見(みる)
        五(ご) 口(くち) 校(こう) 左(ひだり) 三(さん) 山(やま) 子(こ) 四(し) 糸(いと) 字(じ)
        耳(みみ) 七(しち) 車(くるま) 手(て) 十(じゅう) 出(でる) 女(おんな) 小(ちいさい) 上(うえ) 森(もり)
        人(ひと) 水(みず) 正(ただしい) 生(いきる) 青(あお) 夕(ゆう) 石(いし) 赤(あか) 千(せん) 川(かわ)
        先(さき) 早(はやい) 草(くさ) 足(あし) 村(むら) 大(おおきい) 男(おとこ) 竹(たけ) 中(なか) 虫(むし)
        町(まち) 天(てん) 田(た) 土(つち) 二(に) 日(ひ) 入(はいる) 年(とし) 白(しろ) 八(はち)
        百(ひゃく) 文(ぶん) 木(き) 本(ほん) 名(なまえ) 目(め) 立(たつ) 力(ちから) 林(はやし) 六(ろく)`) },
  ],
  g5: [
    { id: "kanji_a", emoji: "漢", name: "漢字（5年）その1",
      chars: _kanji(`賀(ガ) 快(こころよい) 慣(なれる) 眼(まなこ) 基(もと) 寄(よる) 規(キ) 技(わざ)
        逆(ぎゃく) 久(ひさしい) 旧(キュウ) 居(いる) 許(ゆるす) 境(さかい) 均(キン) 禁(キン)
        句(ク) 群(むれ) 経(へる) 潔(いさぎよい)`) },
    { id: "kanji_b", emoji: "字", name: "漢字（5年）その2",
      chars: _kanji(`件(ケン) 券(ケン) 険(けわしい) 検(ケン) 限(かぎる) 現(あらわれる) 減(へる) 故(ゆえ)
        個(コ) 護(ゴ) 効(きく) 厚(あつい) 耕(たがやす) 鉱(コウ) 構(かまえる) 興(おこる)
        講(コウ) 混(まじる) 査(サ) 際(きわ)`) },
  ],
};
